### ISSUE TITLE
EventEmitter memory leak detected seems to stem from seneca

### ISSUE THREAD

**Issue by devotox** [senecajs/gate-executor#7]
```
    |
api_1             | [ Nodemon ][ Error ] Trace
api_1             |     at GateExecutor.addListener (events.js:252:17)
api_1             |     at GateExecutor.once (events.js:278:8)
api_1             |     at Seneca.api_ready [as ready] (/var/app/current/api/node_modules/seneca/seneca.js:923:30)
api_1             |     at meta.export (/var/app/current/api/node_modules/seneca-web/web.js:661:14)
api_1             |     at Layer.handle [as handle_request] (/var/app/current/api/node_modules/express/lib/router/layer.js:95:5)
api_1             |     at trim_prefix (/var/app/current/api/node_modules/express/lib/router/index.js:312:13)
api_1             |     at /var/app/current/api/node_modules/express/lib/router/index.js:280:7
api_1             |     at Function.process_params (/var/app/current/api/node_modules/express/lib/router/index.js:330:12)
api_1             |     at next (/var/app/current/api/node_modules/express/lib/router/index.js:271:10)
api_1             |     at SessionStrategy.strategy.pass (/var/app/current/api/node_modules/passport/lib/middleware/authenticate.js:325:9)
api_1             |     at SessionStrategy.authenticate (/var/app/current/api/node_modules/passport/lib/strategies/session.js:71:10)
api_1             |     at attempt (/var/app/current/api/node_modules/passport/lib/middleware/authenticate.js:348:16)
api_1             |     at authenticate (/var/app/current/api/node_modules/passport/lib/middleware/authenticate.js:349:7)
api_1             |     at Layer.handle [as handle_request] (/var/app/current/api/node_modules/express/lib/router/layer.js:95:5)
api_1             |     at trim_prefix (/var/app/current/api/node_modules/express/lib/router/index.js:312:13)
api_1             |     at /var/app/current/api/node_modules/express/lib/router/index.js:280:7
api_1             |

```

I believe this is GateExecutor adding listeners and not removing them

**Comment by rjrodger** [comment]
Latest version is not an EventEmitter which should close this.
